fix_version: 4.4
dlm: '|'
tag_dict: 
  TransactTime: 60
  OrdStatus: 39
  OrdType: 40
  ExecType: 150
  LeavesQty: 151
  CheckSum: 10
  ClOrdID: 11
  CumQty: 14
  ExecID: 17
  MsgSeqNum: 34
  TargetCompID: 56
  type: 35
  order_id: 37
  total_qty: 38
  ask_price: 44
  user_id: 49
  order_stamp: 52
  side: 54
  product_id: 55
msg_dict:
  Advertisement: 7
  AllocationInstruction: J
  AllocationInstructionAck: P
  AllocationReport: AS
  AllocationReportAck: AT
  AssignmentReport: AW
  BidRequest: k
  BidResponse: l
  BusinessMessageReject: j
  CollateralAssignment: AY
  CollateralInquiry: BB
  CollateralInquiryAck: BG
  CollateralReport: BA
  CollateralRequest: AX
  CollateralResponse: AZ
  Confirmation: AK
  ConfirmationAck: AU
  ConfirmationRequest: BH
  CrossOrderCancel/ReplaceRequest: t
  CrossOrderCancelRequest: u
  DerivativeSecurityList: AA
  DerivativeSecurityListRequest: z
  Don'tKnowTrade: Q
  Email: C
  ExecutionReport: 8
  Heartbeat: 0
  IOI: 6
  ListCancelRequest: K
  ListExecute: L
  ListStatus: N
  ListStatusRequest: M
  ListStrikePrice: m
  Logon: A
  Logout: 5
  MarketData-IncrementalRefresh: X
  MarketDataRequest: V
  MarketDataRequestReject: Y
  MarketData-Snapshot/FullRefresh: W
  MassQuote: i
  MassQuoteAcknowledgement: b
  MultilegOrderCancel/Replace: AC
  NetworkCounterpartySystemStatusRequest: BC
  NetworkCounterpartySystemStatusResponse: BD
  NewOrderCross: s
  NewOrderList: E
  NewOrderMultileg: AB
  NewOrderSingle: D
  News: B
  OrderCancel/ReplaceRequest: G
  OrderCancelReject: 9
  OrderCancelRequest: F
  OrderMassCancelReport: r
  OrderMassCancelRequest: q
  OrderMassStatusRequest: AF
  OrderStatusRequest: H
  PositionMaintenanceReport: AM
  PositionMaintenanceRequest: AL
  PositionReport: AP
  Quote: S
  QuoteCancel: Z
  QuoteRequest: R
  QuoteRequestReject: AG
  QuoteResponse: AJ
  QuoteStatusReport: AI
  QuoteStatusRequest: a
  RegistrationInstructions: o
  RegistrationInstructionsResponse: p
  Reject: 3
  RequestForPositions: AN
  RequestforPositionsAck: AO
  ResendRequest: 2
  RFQRequest: AH
  SecurityDefinition: d
  SecurityDefinitionRequest: c
  SecurityList: y
  SecurityListRequest: x
  SecurityStatus: f
  SecurityStatusRequest: e
  SecurityTypeRequest: v
  SecurityTypes: w
  SequenceReset: 4
  SettlementInstructionRequest: AV
  SettlementInstructions: T
  TestRequest: 1
  TradeCaptureReport: AE
  TradeCaptureReportAck: AR
  TradeCaptureReportRequest: AD
  TradeCaptureReportRequestAck: AQ
  TradingSessionStatus: h
  TradingSessionStatusRequest: g
  UserRequest: BE
  UserResponse: BF
  XMLMessage: n
